TARGET = FFT
OBJS = fft.o
#CFLAGS := -O3 -pthread -D_POSIX_C_SOURCE=200112 -g -static /home/DREXEL/sn446/profilers/valgrind_3.8/valgrind_newbranch/callgrind/wrapper.o # Last 3 added by Sid
CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112

include Makefile.config

